# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'welcomeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(501, 573)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setGeometry(QtCore.QRect(0, -10, 501, 591))
        self.bgwidget.setStyleSheet("\n"
"QWidget#bgwidget{\n"
"background-color:qconicalgradient(cx:0.5, cy:0.5, angle:0, stop:0 rgba(35, 40, 3, 255), stop:0.16 rgba(136, 106, 22, 255), stop:0.225 rgba(166, 140, 41, 255), stop:0.285 rgba(204, 181, 74, 255), stop:0.345 rgba(235, 219, 102, 255), stop:0.415 rgba(245, 236, 112, 255), stop:0.52 rgba(209, 190, 76, 255), stop:0.57 rgba(187, 156, 51, 255), stop:0.635 rgba(168, 142, 42, 255), stop:0.695 rgba(202, 174, 68, 255), stop:0.75 rgba(218, 202, 86, 255), stop:0.815 rgba(208, 187, 73, 255), stop:0.88 rgba(187, 156, 51, 255), stop:0.935 rgba(137, 108, 26, 255), stop:1 rgba(35, 40, 3, 255))}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(170, 110, 181, 51))
        self.label.setStyleSheet("font: 25pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(200, 50, 121, 51))
        self.label_2.setStyleSheet("font: 36pt \"MS Shell Dlg 2\";color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.pushButton_signup = QtWidgets.QPushButton(self.bgwidget)
        self.pushButton_signup.setGeometry(QtCore.QRect(120, 200, 271, 41))
        self.pushButton_signup.setStyleSheet("border-radius:20px;\n"
"background-color:qconicalgradient(cx:0.102, cy:0.119273, angle:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(191, 6, 6, 255));\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)")
        self.pushButton_signup.setObjectName("pushButton_signup")
        self.pushButton_myInfo = QtWidgets.QPushButton(self.bgwidget)
        self.pushButton_myInfo.setGeometry(QtCore.QRect(120, 270, 271, 41))
        self.pushButton_myInfo.setStyleSheet("border-radius:20px;\n"
"background-color:qconicalgradient(cx:0.102, cy:0.119273, angle:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(191, 6, 6, 255));\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)")
        self.pushButton_myInfo.setObjectName("pushButton_myInfo")
        self.pushButton_callUber = QtWidgets.QPushButton(self.bgwidget)
        self.pushButton_callUber.setGeometry(QtCore.QRect(120, 340, 271, 41))
        self.pushButton_callUber.setStyleSheet("border-radius:20px;\n"
"background-color:qconicalgradient(cx:0.102, cy:0.119273, angle:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(191, 6, 6, 255));\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)")
        self.pushButton_callUber.setObjectName("pushButton_callUber")
        self.pushButton_drivingSignup = QtWidgets.QPushButton(self.bgwidget)
        self.pushButton_drivingSignup.setGeometry(QtCore.QRect(120, 410, 271, 41))
        self.pushButton_drivingSignup.setStyleSheet("border-radius:20px;\n"
"background-color:qconicalgradient(cx:0.102, cy:0.119273, angle:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(191, 6, 6, 255));\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"color:rgb(255, 255, 255)")
        self.pushButton_drivingSignup.setObjectName("pushButton_drivingSignup")
        self.pushButton_exit = QtWidgets.QPushButton(self.bgwidget)
        self.pushButton_exit.setGeometry(QtCore.QRect(120, 480, 271, 41))
        self.pushButton_exit.setStyleSheet("border-radius:20px;\n"
"background-color:qconicalgradient(cx:0.102, cy:0.119273, angle:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(191, 6, 6, 255));\n"
"font: 16pt \"MS Shell Dlg 2\";\n"
"\n"
"color:rgb(255, 255, 255)")
        self.pushButton_exit.setObjectName("pushButton_exit")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Hoş Geldiniz"))
        self.label_2.setText(_translate("Dialog", "UBER"))
        self.pushButton_signup.setText(_translate("Dialog", "Kayıt Ol"))
        self.pushButton_myInfo.setText(_translate("Dialog", "Kişisel Bilgilerim"))
        self.pushButton_callUber.setText(_translate("Dialog", "Uber Çağır"))
        self.pushButton_drivingSignup.setText(_translate("Dialog", "Sürücü Başvuru"))
        self.pushButton_exit.setText(_translate("Dialog", "Çıkış"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
